import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import parser from 'svelte-eslint-parser';

/** @type {import('eslint').Linter.Config[]} */
export default [
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs['flat/recommended'],
	prettier,
	...svelte.configs['flat/prettier'],
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node
			}
		}
	},
	{
		files: ['**/*.svelte'],
		languageOptions: {
			parser: parser,
			ecmaVersion: 5,
			sourceType: 'script',

			parserOptions: {
				parser: '@typescript-eslint/parser'
			}
		}
	},
	{
		ignores: ['build/', '.svelte-kit/', 'dist/']
	},
	{
		files: ['*.ts'],
		rules: {
			'no-undef': 'off'
		}
	},
	{
		// Generated by oazapfts and marked DO NOT MODIFY. It used to carry its own
		// eslint-disable pragma for this rule, but oazapfts no longer emits one and a
		// hand-added pragma would not survive the next `make api`. Every other rule
		// still applies, so a genuinely broken generation still surfaces.
		files: ['src/lib/immichFrameApi.ts'],
		rules: {
			'@typescript-eslint/no-explicit-any': 'off'
		}
	}
];
