#!/bin/sh
# Fullstack language adapter for the audit system (C#/.NET + TypeScript/Svelte).
#
# The audit core (audit/audit.sh, audit/scan.sh, audit/arch.sh) is
# language-agnostic. Every project-specific decision — which files to track, how
# to prioritise them, the build/test commands embedded in generated prompts, and
# the catalog of static analyzers — lives here. The core sources exactly one
# adapter, selected by AUDIT_ADAPTER, via `. audit/adapters/${AUDIT_ADAPTER}.sh`.
#
# ImmichFrame is two stacks in one repo (an ASP.NET Core 8 API plus a SvelteKit
# SPA), so this is deliberately ONE composite adapter rather than one per
# language: the core can only source a single file, and a `dotnet.sh` /
# `svelte.sh` split would force two disjoint databases over one codebase. Hence
# the name. Both halves are covered here: every seam below handles C# and
# TypeScript/Svelte paths, and the scan catalog drives both toolchains.
#
# See audit/ADAPTERS.md for the contract and audit/adapters/go.sh for the
# reference implementation this follows.
#
# Architecture members (audit_arch_*) are deliberately ABSENT, so `arch-sweep`
# is NOT available under this adapter. The core's placeholder substitution
# covers only the optional Section A/B/D/E bodies; audit/arch.sh:45 calls
# audit_arch_preflight unguarded, so running arch-sweep here dies with
# "audit_arch_preflight: not found". The audit-arch Make target refuses with a
# clear message instead of entering that path. Authoring them is a later task.
#
# POSIX sh only. The core is `#!/bin/sh` and SOURCES this file, so a bashism
# here breaks the core itself: no arrays, no `[[`, no `local`, no `${var,,}`.
#
# ---------------------------------------------------------------------------
# Adapter contract (functions/variables the core calls)
# ---------------------------------------------------------------------------
#
# Discovery & priority (used by audit/audit.sh cmd_sync):
#   audit_discover_sources      Repo-relative source paths, one per line.
#   audit_priority_score <path> Integer 0-100; higher = swept sooner.
#   audit_trivial_comment_regex ERE for comment-only lines (optional hook).
#
# Verify commands (used by audit/audit.sh prompt templates):
#   audit_verify_build_cmd   Print the build command string (no trailing NL).
#   audit_verify_test_cmd    Print the test command string (no trailing NL).
#
# Scan tool catalog (used by audit/scan.sh). The core owns the generic harness
# (file-id cache, sql_escape/rel_path/truncate_str/count_lines, apply_batch,
# batch header/footer, file sync, "all analyzers missing" check, summary
# rendering). The adapter owns the tools:
#   AUDIT_SCAN_TOOLS        Space-separated, ordered list of tool ids.
#   scan_<id>               One driver per id; sets the counter/state vars.
#   audit_scan_label <id>   Display name for the summary table.
#   audit_scan_state <id>   "ran" or "missing".
#   audit_scan_new/_dup/_skip <id>   Per-tool counters.
#
# The drivers rely on these being defined by the core before they run: DB,
# REPO_ROOT, TMP_DIR, FILES_CACHE, and the helper functions lookup_fid,
# sql_escape, rel_path, truncate_str, count_lines, apply_batch,
# write_batch_header, write_batch_footer.

# ---------------------------------------------------------------------------
# Discovery & priority
# ---------------------------------------------------------------------------

# The four C# project directories of ImmichFrame.sln. Named explicitly rather
# than discovered from the .sln so that discovery never sweeps in stray *.cs
# under docs/, misc/ or a scratch directory.
AUDIT_CS_PROJECTS="ImmichFrame.Core ImmichFrame.WebApi ImmichFrame.Core.Tests ImmichFrame.WebApi.Tests"

# The SvelteKit project root, the one source under it that is never audited, and
# the one hand-written source that lives OUTSIDE src/.
#
# immichFrameApi.ts is generated by oazapfts from openApi/swagger.json and is
# marked DO NOT MODIFY; tracking it would queue an agent to hand-edit generated
# code, exactly as the obj/ and bin/ exclusions above avoid for C#.
#
# static/ is otherwise images and a webmanifest, but pwa-service-worker.js is
# 100 lines of hand-written security-relevant logic: it caches a bearer auth
# secret received over postMessage and injects 'Authorization: Bearer <secret>'
# onto intercepted video-stream requests. It is named explicitly rather than
# swept up by a static/*.js glob, for the same reason AUDIT_CS_PROJECTS is a
# list and not a find: a future minified vendor drop in static/ must not silently
# enter the audit queue.
AUDIT_WEB_ROOT="immichFrame.Web"
AUDIT_WEB_GENERATED="immichFrame.Web/src/lib/immichFrameApi.ts"
AUDIT_WEB_SERVICE_WORKER="immichFrame.Web/static/pwa-service-worker.js"

# audit_discover_sources: repo-relative list of files to track.
#
# Sourced from git's index (`git ls-files`), like go.sh, NOT from a bare find.
# Rooting a find at the project directories does not keep untracked files out —
# a C# scratch or work-in-progress file has to live inside a project to compile,
# so it lands squarely in the search path. Tracking those is actively harmful:
# they consume sweep-queue slots, and `git log -1` reports no history for them,
# so they enter the files table with last_commit='unknown' and their staleness
# path never fires (the core treats an empty/unknown hash as non-trivial and can
# never re-stamp coverage against it).
#
# The obj/ and bin/ exclusions stay path-based rather than leaning on
# .gitignore, so the intent survives a gitignore edit. Both hold generated
# compiler output (AssemblyInfo, GlobalUsings, the NSwag-generated ImmichApi) —
# machine-written, regenerated on every build, and meaningless to audit.
#
# Directory.Packages.props is tracked as a source file even though it is not
# C#: `dotnet list package --vulnerable` reports per *package*, but a finding
# row needs a file_id from a tracked path. This repo uses Central Package
# Management, so that one file holds every version and is where a bump is
# actually made — it is the correct owner for dependency CVEs. See
# scan_vulnerable below.
#
# The `[ -f ]` filter drops index entries whose working-tree copy is absent
# (an `rm` without `git rm`), which would otherwise abort cmd_sync's `wc -l`
# under set -e. git ls-files emits bare repo-relative paths, which is already
# the contract (the core strips a leading "./" defensively anyway).
#
# The frontend half is rooted at immichFrame.Web/src, with two named additions.
# src/ is the bulk of the hand-written code; what sits above it is mostly build
# configuration (vite/svelte/tailwind/postcss config, tsconfig) that no file
# sweep should queue. The exceptions are named explicitly:
#
#   package.json  tracked as a source file even though it is not TypeScript —
#                 `npm audit` reports per *package* and a finding row needs a
#                 file_id, so package.json owns the dependency advisories the
#                 way Directory.Packages.props owns the NuGet ones. See
#                 scan_npmaudit.
#   static/pwa-service-worker.js  NOT build configuration: hand-written code
#                 that handles a bearer credential (see the constant above).
#                 ESLint already lints it, so leaving it untracked did not make
#                 it unanalysed — it made every finding against it get thrown
#                 away as an untracked-path skip.
audit_discover_sources() {
    for d in $AUDIT_CS_PROJECTS; do
        git ls-files -- "$d/*.cs"
    done \
    | grep -Ev '(^|/)(obj|bin)/' \
    | while IFS= read -r p; do [ -f "$p" ] && printf '%s\n' "$p"; done
    git ls-files -- 'Directory.Packages.props' \
    | while IFS= read -r p; do [ -f "$p" ] && printf '%s\n' "$p"; done
    git ls-files -- "$AUDIT_WEB_ROOT/src/*.ts" "$AUDIT_WEB_ROOT/src/*.svelte" \
                    "$AUDIT_WEB_ROOT/src/*.js" \
    | grep -Fxv "$AUDIT_WEB_GENERATED" \
    | while IFS= read -r p; do [ -f "$p" ] && printf '%s\n' "$p"; done
    git ls-files -- "$AUDIT_WEB_ROOT/package.json" \
    | while IFS= read -r p; do [ -f "$p" ] && printf '%s\n' "$p"; done
    git ls-files -- "$AUDIT_WEB_SERVICE_WORKER" \
    | while IFS= read -r p; do [ -f "$p" ] && printf '%s\n' "$p"; done
}

# audit_priority_score <path>: priority score for a repo-relative path.
#
# Path-prefix scoring only — no git-churn weighting, because the core already
# surfaces staleness separately (v_next_audit_target orders on coverage age).
# The *.Tests/* arm comes FIRST so that a test file never inherits the score of
# the production area it mirrors.
audit_priority_score() {
    priority=50
    case "$1" in
        # Audited, but last: no production blast radius.
        *.Tests/*)                              priority=25 ;;
        # Settings loading — holds the auth secret, Immich API keys, webhooks.
        ImmichFrame.WebApi/Helpers/Config/*)    priority=95 ;;
        # The composition root: DI, middleware order, auth wiring.
        ImmichFrame.WebApi/Program.cs)          priority=90 ;;
        # Auth middleware, SanitizeString, the profile registry.
        ImmichFrame.WebApi/Helpers/*)           priority=85 ;;
        # Request handling — client-supplied input lands here.
        ImmichFrame.WebApi/Controllers/*)       priority=80 ;;
        # Asset pools: the busiest and most intricate area of the codebase.
        ImmichFrame.Core/Logic/*)               priority=70 ;;
        # Outbound HTTP and credential handling.
        ImmichFrame.Core/Api/*)                 priority=65 ;;
        ImmichFrame.Core/Services/*)            priority=65 ;;
        # DTO boundary — the client-leak surface.
        ImmichFrame.WebApi/Models/*)            priority=55 ;;
        ImmichFrame.Core/Models/*)              priority=55 ;;

        # --- frontend ---------------------------------------------------
        # Nothing here outranks the C# config surface at 95, which is where
        # the auth secret is issued and stored. The SPA only ever holds a
        # copy of one, and only in the service worker.
        #
        # Ordering inside this block is load-bearing. A `case` pattern's `*`
        # matches '/' too, so `immichFrame.Web/src/lib/*.ts` also matches
        # stores/, hooks/, components/ and constants/. Those four arms must
        # therefore come FIRST; the .ts arm then only ever sees files sitting
        # directly in src/lib.

        # The PWA service worker: the only frontend file that holds a
        # credential. It caches the bearer auth secret and signs outbound
        # video-stream requests with it, so it outranks everything else on
        # this side of the stack — but stays below the C# config surface at
        # 95, which is where the secret is actually issued.
        immichFrame.Web/static/pwa-service-worker.js) priority=75 ;;
        # Entry points and data loading (+page.ts / +layout.ts run first).
        immichFrame.Web/src/routes/*)           priority=65 ;;
        # Shared mutable state and the lifecycle hooks that drive it.
        immichFrame.Web/src/lib/stores/*)       priority=60 ;;
        immichFrame.Web/src/lib/hooks/*)        priority=60 ;;
        # Presentation: bugs here are visible, not structural.
        immichFrame.Web/src/lib/components/*)   priority=50 ;;
        # Literal tables — lowest-value audit target in the repo.
        immichFrame.Web/src/lib/constants/*)    priority=35 ;;
        # Cross-cutting helpers directly under src/lib (utils, constants, index).
        immichFrame.Web/src/lib/*.ts)           priority=60 ;;
        # Dependency advisories land here; see scan_npmaudit.
        immichFrame.Web/package.json)           priority=50 ;;

        # Everything else in Core, Directory.Packages.props, and
        # immichFrame.Web/src/app.d.ts keep 50.
    esac
    printf '%s' "$priority"
}

# audit_trivial_comment_regex: ERE for comment-only lines, repo-wide.
#
# The core takes ONE regex for the whole repo, so this covers both languages'
# line-comment forms:
#
#   //  — C#, TypeScript and JavaScript
#   <!-- ... -->  — Svelte markup (single-line only)
#
# Two properties have to hold on both arms.
#
# (1) A comment whose marker is GLUED to the text is meaningful, never trivial.
#     '///' is a C# XML doc comment (this codebase uses '/// <summary>' to
#     record design rationale in ProfileRegistry.cs and ProfileServices.cs) and
#     in TypeScript a triple-slash directive ('/// <reference types="..." />')
#     that changes what the compiler sees. '//nolint' and '//go:build' are the
#     same shape. Requiring whitespace-or-EOL after '//' excludes them all, and
#     '/**' JSDoc never matches because it has one slash before the star.
#
# (2) A comment whose FIRST TOKEN is a directive is equally meaningful — and in
#     TS/JS/Svelte, unlike C# and Go, those carry a SPACE after the opener:
#
#       // @ts-expect-error          // @ts-ignore
#       // eslint-disable-next-line  // prettier-ignore
#       <!-- svelte-ignore a11y_… -->  <!-- @component … -->
#
#     Silencing a lint rule is precisely the edit that must expire coverage:
#     the scan seeds no-explicit-any and no-unused-vars, which is what a
#     developer reaches for a disable comment to hide. Without this the core
#     re-stamps coverage and the audit never revisits the file.
#
#     git takes one ERE and POSIX has no negative lookahead, so the property is
#     spelled positively: the first token of the comment body must contain
#     neither '@' nor '-'  ([^@[:space:]-]*), and anything after it is
#     unconstrained (so '// see https://x/a-b' stays trivial — only the leading
#     token is a directive slot). This deliberately errs toward NON-trivial: a
#     prose comment opening on a hyphenated word is treated as meaningful,
#     which is the safe direction per ADAPTERS.md — never re-stamp on doubt.
#
# The markup arm additionally requires the comment to open and close on the same
# line, so a multi-line <!-- --> block falls to the conservative default, as C#
# /* */ blocks already do. Its body is spelled ([^-]|-[^-]|--[^>])* — "anything
# up to the FIRST -->" — rather than the obvious '.*', which is greedy and would
# run to the LAST --> on the line, calling '<!-- a --> markup <!-- b -->' a
# comment-only line.
audit_trivial_comment_regex() {
    printf '%s' '^[[:space:]]*(//([[:space:]]+[^@[:space:]-]*([[:space:]].*)?)?$|<!--([[:space:]]+[^@[:space:]-]*([[:space:]]([^-]|-[^-]|--[^>])*)?)?-->[[:space:]]*$)'
}

# ---------------------------------------------------------------------------
# Verify commands embedded in generated prompts
# ---------------------------------------------------------------------------

# One repo, two toolchains, and the core takes a single string for each — so
# both are named on one line with a hint telling the agent which to pick. These
# strings are prompt text: the core interpolates them into sweep/deep-sweep/fix
# prompts (some inside backticks) and never executes them, so the trailing hint
# is read, not run. No backticks in the text, for that reason.
audit_verify_build_cmd() {
    printf '%s' 'dotnet build ImmichFrame.sln (C#) or npm --prefix immichFrame.Web run build (frontend) -- run whichever matches the files under audit'
}
audit_verify_test_cmd() {
    printf '%s' 'dotnet test ImmichFrame.sln (C#) or npm --prefix immichFrame.Web run check (frontend) -- run whichever matches the files under audit'
}

# ---------------------------------------------------------------------------
# Scan tool catalog
# ---------------------------------------------------------------------------

# audit_cs_diagnostic_category <diagnostic-id>: map a Roslyn diagnostic id to a
# findings.category value. Shared by scan_build and scan_roslynator so the same
# rule cannot be filed as two different categories depending on which analyzer
# host happened to report it — both hosts emit the same id namespace.
#   NUnit*   the NUnit analyzers speak about test correctness
#   CA*/IDE* code-quality and style suggestions, not defects
#   RCS*     Roslynator's own refactoring rules
#   ASP*     ASP.NET Core usage suggestions ("Suggest using IHeaderDictionary
#            properties", "Use AddAuthorizationBuilder") — advice, not defects
#   SYSLIB*  source-generator/obsoletion advice ("Convert to
#            'GeneratedRegexAttribute'") — likewise advice
#   default  compiler CS* diagnostics: nullability holes and friends, the one
#            family here that really is a latent defect
audit_cs_diagnostic_category() {
    case "$1" in
        NUnit*)                       printf '%s' 'tests' ;;
        CA*|IDE*|RCS*|ASP*|SYSLIB*)   printf '%s' 'refactoring' ;;
        *)                            printf '%s' 'bugs' ;;
    esac
}

# Ordered tool ids. The core iterates this for running, the all-missing check,
# the new-findings tally, and the summary (preserving [1/3]..[3/3] order).
AUDIT_SCAN_TOOLS="build vulnerable roslynator eslint sveltecheck npmaudit"

# Per-tool counters/state. Held as shell variables; surfaced via the
# audit_scan_* accessors below and printed by the core's summary. A driver's
# parse loop runs in a subshell (it is the right-hand side of a pipe), so it
# CANNOT assign these directly — it appends a marker line to a temp file and the
# driver body counts those files after the loop, exactly as go.sh does.
BUILD_NEW=0;       BUILD_DUP=0;       BUILD_SKIP=0;       BUILD_STATE=missing
VULNERABLE_NEW=0;  VULNERABLE_DUP=0;  VULNERABLE_SKIP=0;  VULNERABLE_STATE=missing
ROSLYNATOR_NEW=0;  ROSLYNATOR_DUP=0;  ROSLYNATOR_SKIP=0;  ROSLYNATOR_STATE=missing
ESLINT_NEW=0;      ESLINT_DUP=0;      ESLINT_SKIP=0;      ESLINT_STATE=missing
SVELTECHECK_NEW=0; SVELTECHECK_DUP=0; SVELTECHECK_SKIP=0; SVELTECHECK_STATE=missing
NPMAUDIT_NEW=0;    NPMAUDIT_DUP=0;    NPMAUDIT_SKIP=0;    NPMAUDIT_STATE=missing

# Accessors mapping a tool id to its display name and counter/state vars. These
# keep the core's harness free of any tool-specific variable names.
audit_scan_label() {
    case "$1" in
        build)      printf '%s' 'dotnet build' ;;
        vulnerable) printf '%s' 'nuget-vuln' ;;
        roslynator) printf '%s' 'roslynator' ;;
        eslint)     printf '%s' 'eslint' ;;
        sveltecheck) printf '%s' 'svelte-check' ;;
        npmaudit)   printf '%s' 'npm-audit' ;;
    esac
}

audit_scan_state() {
    case "$1" in
        build)      printf '%s' "$BUILD_STATE" ;;
        vulnerable) printf '%s' "$VULNERABLE_STATE" ;;
        roslynator) printf '%s' "$ROSLYNATOR_STATE" ;;
        eslint)     printf '%s' "$ESLINT_STATE" ;;
        sveltecheck) printf '%s' "$SVELTECHECK_STATE" ;;
        npmaudit)   printf '%s' "$NPMAUDIT_STATE" ;;
    esac
}

audit_scan_new() {
    case "$1" in
        build)      printf '%s' "$BUILD_NEW" ;;
        vulnerable) printf '%s' "$VULNERABLE_NEW" ;;
        roslynator) printf '%s' "$ROSLYNATOR_NEW" ;;
        eslint)     printf '%s' "$ESLINT_NEW" ;;
        sveltecheck) printf '%s' "$SVELTECHECK_NEW" ;;
        npmaudit)   printf '%s' "$NPMAUDIT_NEW" ;;
    esac
}

audit_scan_dup() {
    case "$1" in
        build)      printf '%s' "$BUILD_DUP" ;;
        vulnerable) printf '%s' "$VULNERABLE_DUP" ;;
        roslynator) printf '%s' "$ROSLYNATOR_DUP" ;;
        eslint)     printf '%s' "$ESLINT_DUP" ;;
        sveltecheck) printf '%s' "$SVELTECHECK_DUP" ;;
        npmaudit)   printf '%s' "$NPMAUDIT_DUP" ;;
    esac
}

audit_scan_skip() {
    case "$1" in
        build)      printf '%s' "$BUILD_SKIP" ;;
        vulnerable) printf '%s' "$VULNERABLE_SKIP" ;;
        roslynator) printf '%s' "$ROSLYNATOR_SKIP" ;;
        eslint)     printf '%s' "$ESLINT_SKIP" ;;
        sveltecheck) printf '%s' "$SVELTECHECK_SKIP" ;;
        npmaudit)   printf '%s' "$NPMAUDIT_SKIP" ;;
    esac
}

# ---- dotnet build ----------------------------------------------------
# The C# compiler and the Roslyn analyzers bundled with the SDK (CA*, CS*,
# NUnit*, ASP*) are themselves a static analyzer; the build is the cheapest way
# to run them.
scan_build() {
    echo "[1/6] dotnet build..."
    if ! command -v dotnet >/dev/null 2>&1; then
        echo "  [!] dotnet not installed — install the .NET 8 SDK"
        return
    fi
    BUILD_STATE=ran
    raw="$TMP_DIR/build.raw"
    out="$TMP_DIR/build.txt"
    # --no-incremental is load-bearing, not a tidy-up: MSBuild replays NO
    # diagnostics for a project it considers up to date, so a plain
    # `dotnet build` on an unchanged tree emits zero warnings. Without this the
    # driver would silently find nothing on every run after the first and the
    # zero would read as "dedup is working".
    # Exit is non-zero whenever the build has errors — those are exactly the
    # diagnostics we want, so tolerate it and let the parse decide.
    dotnet build ImmichFrame.sln --no-incremental \
        > "$raw" 2>"$TMP_DIR/build.err" || true

    # MSBuild prints every diagnostic twice — once inline as the project
    # compiles and once in the end-of-build summary — byte for byte. Deduping
    # here keeps the reported `duplicate` count honest instead of showing half
    # the findings as dupes of themselves.
    grep -E '\([0-9]+,[0-9]+\): (warning|error) ' "$raw" | sort -u > "$out" || true
    if [ ! -s "$out" ]; then
        return
    fi

    batch="$TMP_DIR/build.sql"
    write_batch_header "$batch"
    # Diagnostic lines look like:
    #   /abs/path/File.cs(12,5): warning CS8618: message [/abs/path/Proj.csproj]
    # Emit one "path|line|kind|code|message" record each. `message` is LAST so
    # that a '|' inside it lands in the final read variable untouched (POSIX
    # read assigns the unsplit remainder to the last name).
    awk '{
        if (match($0, /\([0-9]+,[0-9]+\): (warning|error) [A-Za-z][A-Za-z0-9]+: /) == 0) next
        file = substr($0, 1, RSTART - 1)
        tok  = substr($0, RSTART, RLENGTH)
        msg  = substr($0, RSTART + RLENGTH)
        sub(/ \[[^][]*\]$/, "", msg)          # drop the trailing [Project.csproj]
        ln = tok;   sub(/^\(/, "", ln);       sub(/,.*$/, "", ln)
        kind = tok; sub(/^\([0-9]+,[0-9]+\): /, "", kind); sub(/ .*$/, "", kind)
        code = tok; sub(/^\([0-9]+,[0-9]+\): (warning|error) /, "", code); sub(/:.*$/, "", code)
        print file "|" ln "|" kind "|" code "|" msg
    }' "$out" \
    | while IFS='|' read -r file line kind code msg; do
        [ -z "$file" ] && continue
        rel="$(rel_path "$file")"
        fid="$(lookup_fid "$rel")"
        if [ -z "$fid" ]; then
            echo "  [skip] untracked path: $rel" >&2
            echo "SKIP" >> "$TMP_DIR/build.skips"
            continue
        fi
        case "$kind" in
            error) severity=high   ;;
            *)     severity=medium ;;
        esac
        category="$(audit_cs_diagnostic_category "$code")"
        title="$(truncate_str 200 "[$code] $msg")"
        desc="$(truncate_str 2000 "$msg")"
        ft="$(sql_escape "$title")"
        fd="$(sql_escape "$desc")"
        printf "INSERT OR IGNORE INTO findings (file_id, line, tool, source, severity, category, title, description, status) VALUES (%s, %s, 'build', 'static-tool', '%s', '%s', '%s', '%s', 'open');\n" \
            "$fid" "$line" "$severity" "$category" "$ft" "$fd" >> "$batch"
        echo "INS" >> "$TMP_DIR/build.ins"
    done
    attempted="$(count_lines "$TMP_DIR/build.ins")"
    BUILD_SKIP="$(count_lines "$TMP_DIR/build.skips")"
    write_batch_footer "$batch"

    if [ "$attempted" -gt 0 ]; then
        result="$(apply_batch build "$batch" "$attempted")"
        BUILD_NEW="${result% *}"
        BUILD_DUP="${result#* }"
    fi
}

# ---- nuget vulnerability audit ---------------------------------------
# `dotnet list package --vulnerable` reports per package, not per source line.
# Every finding is attributed to Directory.Packages.props: with Central Package
# Management that file holds every pinned version and is where the bump is
# made. Transitive packages have no entry there, so they get line 0.
scan_vulnerable() {
    echo "[2/6] dotnet list package --vulnerable..."
    if ! command -v dotnet >/dev/null 2>&1; then
        echo "  [!] dotnet not installed — install the .NET 8 SDK"
        return
    fi
    VULNERABLE_STATE=ran
    raw="$TMP_DIR/vulnerable.raw"
    out="$TMP_DIR/vulnerable.json"
    # --format json is supported by the .NET 8 SDK (verified on 8.0.415).
    # Needs network access to query the NuGet advisory feed; when offline the
    # command still exits cleanly with an empty report, so no findings rather
    # than a failed scan — which is the graceful-degradation behaviour we want.
    dotnet list package --vulnerable --include-transitive --format json \
        > "$raw" 2>"$TMP_DIR/vulnerable.err" || true
    # The SDK can prefix restore/NU* notices before the JSON document; start
    # the payload at the line that opens the object.
    sed -n '/^{/,$p' "$raw" > "$out"
    if ! jq -e . "$out" >/dev/null 2>&1; then
        echo "  [!] no parsable JSON from 'dotnet list package'; see $TMP_DIR/vulnerable.raw" >&2
        return
    fi

    owner="Directory.Packages.props"
    fid="$(lookup_fid "$owner")"
    if [ -z "$fid" ]; then
        echo "  [skip] untracked path: $owner" >&2
        VULNERABLE_SKIP=1
        return
    fi

    # One "id|version|severity|advisoryurl" record per (package, advisory).
    # `unique` collapses the same package reported by several projects — with
    # one shared Directory.Packages.props they would all be the same finding.
    jq -r '[ .projects[]? | .frameworks[]?
             | (.topLevelPackages[]?, .transitivePackages[]?)
             | . as $p
             | ($p.vulnerabilities[]?
                | "\($p.id)|\($p.resolvedVersion)|\(.severity)|\(.advisoryurl)") ]
           | unique | .[]' "$out" > "$TMP_DIR/vulnerable.records" 2>/dev/null \
        || : > "$TMP_DIR/vulnerable.records"

    if [ ! -s "$TMP_DIR/vulnerable.records" ]; then
        return
    fi

    batch="$TMP_DIR/vulnerable.sql"
    write_batch_header "$batch"
    while IFS='|' read -r name version sev url; do
        [ -z "$name" ] && continue
        # Line of the pin in Directory.Packages.props, 0 when absent (which is
        # the normal case for a transitive dependency). -F because package ids
        # are dotted and would otherwise read as regex.
        line="$(grep -Fn "PackageVersion Include=\"$name\"" "$owner" 2>/dev/null | head -1 | cut -d: -f1)"
        [ -z "$line" ] && line=0
        case "$sev" in
            Critical) severity=critical ;;
            High)     severity=high     ;;
            Moderate) severity=medium   ;;
            Low)      severity=low      ;;
            *)        severity=medium   ;;
        esac
        # The advisory id is the last path segment of the URL (GHSA-xxxx-...).
        # Putting it in the title keeps two advisories against the same package
        # as two distinct findings under idx_findings_dedup(file_id, line, tool, title).
        adv="${url##*/}"
        [ -z "$adv" ] && adv="$sev"
        title="$(truncate_str 200 "[$adv] vulnerable package $name $version")"
        desc="$(truncate_str 2000 "$sev severity advisory against $name $version — bump the pin in $owner. $url")"
        ft="$(sql_escape "$title")"
        fd="$(sql_escape "$desc")"
        printf "INSERT OR IGNORE INTO findings (file_id, line, tool, source, severity, category, title, description, status) VALUES (%s, %s, 'vulnerable', 'static-tool', '%s', 'security', '%s', '%s', 'open');\n" \
            "$fid" "$line" "$severity" "$ft" "$fd" >> "$batch"
        echo "INS" >> "$TMP_DIR/vulnerable.ins"
    done < "$TMP_DIR/vulnerable.records"
    attempted="$(count_lines "$TMP_DIR/vulnerable.ins")"
    write_batch_footer "$batch"

    if [ "$attempted" -gt 0 ]; then
        result="$(apply_batch vulnerable "$batch" "$attempted")"
        VULNERABLE_NEW="${result% *}"
        VULNERABLE_DUP="${result#* }"
    fi
}

# ---- roslynator ------------------------------------------------------
# Roslynator re-hosts whatever analyzers the projects already reference (the
# SDK's CA*/CS*/ASP*/SYSLIB* plus NUnit.Analyzers) and reports them at info
# severity — a broader net than the build, which only surfaces what is
# configured as a warning.
#
# Roslynator's OWN rules (RCS*) are not part of that: they ship in the separate
# Roslynator.Analyzers NuGet package, and roslynator.dotnet.cli contains no
# analyzer assembly at all. Without -a the report is 100% other people's
# analyzers and not one RCS diagnostic appears. `make audit-tools` unpacks that
# package under the root below; the driver passes -a when a usable analyzer
# directory is found and says so plainly when it is not.
AUDIT_ROSLYNATOR_ANALYZERS_ROOT="${AUDIT_ROSLYNATOR_ANALYZERS_ROOT:-$HOME/.local/share/roslynator-analyzers/analyzers/dotnet}"

# audit_roslynator_analyzer_dir: print the analyzer directory to hand to -a, or
# nothing if none is usable.
#
# The package ships one tree per Roslyn generation (roslyn3.8, roslyn4.7, ...)
# and which segments exist changes between releases, so the segment is PROBED
# rather than hardcoded: pinning it would mean a version bump in the Makefile
# silently dropped every RCS finding while the scan still reported success.
# A tree with no *.dll (an interrupted or partial unpack) is skipped, so a
# half-written directory cannot pass the probe. Highest generation wins,
# compared on a zero-padded numeric key because a plain string compare would
# order roslyn4.12 below roslyn4.7.
# POSIX sh has no `local`, and this adapter is SOURCED into the core's shell —
# so every plain assignment here is a global in the core's namespace. The
# scratch variables are therefore _af_-prefixed ("adapter fullstack"): without
# it, `key` below would collide by name with audit.sh:232's coverage-sync loop
# variable, and `best`/`seg`/`d` are generic enough to collide with the next
# thing either side grows. Same prefix on every helper added since.
audit_roslynator_analyzer_dir() {
    _af_best=""
    _af_best_key=""
    for _af_dir in "$AUDIT_ROSLYNATOR_ANALYZERS_ROOT"/roslyn*/cs; do
        [ -d "$_af_dir" ] || continue
        ls "$_af_dir"/*.dll >/dev/null 2>&1 || continue
        _af_seg="${_af_dir%/cs}"
        _af_seg="${_af_seg##*/roslyn}"
        _af_key="$(printf '%s' "$_af_seg" | awk -F. '{ printf "%04d%04d", $1, $2 }')"
        if [ -z "$_af_best_key" ] || [ "$_af_key" -gt "$_af_best_key" ]; then
            _af_best="$_af_dir"
            _af_best_key="$_af_key"
        fi
    done
    printf '%s' "$_af_best"
}

scan_roslynator() {
    echo "[3/6] roslynator..."
    if ! command -v roslynator >/dev/null 2>&1; then
        echo "  [!] roslynator not installed — run 'make audit-tools'"
        return
    fi
    xml="$TMP_DIR/roslynator.xml"
    analyzers="$(audit_roslynator_analyzer_dir)"
    # Reset rc rather than relying on "${rc:-0}": rc is a plain shell variable
    # in the sourced adapter, so a value left behind by an earlier driver would
    # otherwise leak into this check.
    rc=0
    # -o is required: without it roslynator only pretty-prints to the console.
    # Exit 1 means "diagnostics reported" — tolerate it; >1 is a real failure.
    # The two invocations are spelled out rather than built up in a variable so
    # that a path containing a space cannot be re-split by the expansion.
    if [ -n "$analyzers" ]; then
        roslynator analyze ImmichFrame.sln -o "$xml" -v q \
            -a "$analyzers" \
            >"$TMP_DIR/roslynator.out" 2>"$TMP_DIR/roslynator.err" || rc=$?
    else
        echo "  [!] RCS rules unavailable: no analyzer assemblies under $AUDIT_ROSLYNATOR_ANALYZERS_ROOT"
        echo "      (run 'make audit-tools'); continuing with the project's own analyzers."
        roslynator analyze ImmichFrame.sln -o "$xml" -v q \
            >"$TMP_DIR/roslynator.out" 2>"$TMP_DIR/roslynator.err" || rc=$?
    fi
    if [ "$rc" -gt 1 ]; then
        echo "  [!] roslynator failed (exit ${rc}); see $TMP_DIR/roslynator.err" >&2
        return
    fi
    # State is set only once the run is known to have succeeded — go.sh sets it
    # before the check, but -a gives that a concrete failure mode: a truncated
    # unpack leaves the directory present, the probe passes, roslynator exits
    # >1, and the summary would read "ran, 0 new" — indistinguishable from a
    # clean scan. Leaving it "missing" makes the bail-out visible.
    ROSLYNATOR_STATE=ran
    if [ ! -s "$xml" ]; then
        return
    fi

    batch="$TMP_DIR/roslynator.sql"
    write_batch_header "$batch"
    # The report is XML, and xmllint/python are not dependencies of this kit, so
    # parse with awk: accumulate the fields of one <Diagnostic> block and flush
    # on </Diagnostic>.
    #
    # The document opens with a <Summary> whose <Diagnostic> entries are ALSO
    # multi-line elements wrapping <Description>/<HelpLink> — what separates
    # them from real findings is that they carry no <FilePath>, so requiring one
    # at flush time is the guard. Every field is additionally reset on each
    # <Diagnostic Id= line, so a block missing its close tag cannot leak state
    # into the next one.
    #
    # <Message> may span several physical lines (any diagnostic whose text
    # contains a newline), so accumulate from <Message> until </Message> and
    # join with a single space, stripping the continuation lines' XML indent —
    # taking only the first line, as this did before, silently truncated them.
    # The text is XML-escaped; unesc() reverses the five predefined entities
    # (&amp; last, or it would double-decode "&amp;lt;"). `message` is emitted
    # LAST so a '|' inside it survives the read below intact.
    awk '
        function unesc(t) {
            gsub(/&lt;/,   "<",  t)
            gsub(/&gt;/,   ">",  t)
            gsub(/&quot;/, "\"", t)
            gsub(/&apos;/, "'"'"'", t)
            gsub(/&amp;/,  "\\&", t)
            return t
        }
        /<Diagnostic Id="/ {
            id = $0; sub(/^.*<Diagnostic Id="/, "", id); sub(/".*$/, "", id)
            sev = ""; msg = ""; fp = ""; ln = ""; inmsg = 0; next
        }
        inmsg == 1 {
            part = $0; sub(/^[[:space:]]+/, "", part)
            if (index(part, "</Message>") > 0) {
                sub(/<\/Message>.*$/, "", part)
                msg = unesc(msg " " part)
                inmsg = 0
            } else {
                msg = msg " " part
            }
            next
        }
        /<Severity>/ { sev = $0; sub(/^.*<Severity>/, "", sev); sub(/<\/Severity>.*$/, "", sev); next }
        /<FilePath>/ { fp  = $0; sub(/^.*<FilePath>/, "", fp);  sub(/<\/FilePath>.*$/, "", fp);  next }
        /<Location Line="/ { ln = $0; sub(/^.*<Location Line="/, "", ln); sub(/".*$/, "", ln); next }
        /<Message>/ {
            msg = $0; sub(/^.*<Message>/, "", msg)
            if (index(msg, "</Message>") > 0) {
                sub(/<\/Message>.*$/, "", msg)
                msg = unesc(msg)
            } else {
                inmsg = 1
            }
            next
        }
        /<\/Diagnostic>/ {
            if (fp != "" && ln != "") print fp "|" ln "|" sev "|" id "|" msg
            sev = ""; msg = ""; fp = ""; ln = ""; inmsg = 0; next
        }
    ' "$xml" \
    | while IFS='|' read -r file line sev id msg; do
        [ -z "$file" ] && continue
        # CS* are compiler diagnostics: scan_build already owns them, at the
        # same file and line, and MSBuild's wording is strictly better because
        # it names the offending symbol ("Non-nullable field '_pool' must ...")
        # where Roslynator re-emits only the generic rule title. Dropping them
        # here is what stops every build finding having a roslynator twin.
        # Not counted as a skip — nothing was missed, it is deliberate routing.
        case "$id" in
            CS*) continue ;;
        esac
        rel="$(rel_path "$file")"
        fid="$(lookup_fid "$rel")"
        if [ -z "$fid" ]; then
            echo "  [skip] untracked path: $rel" >&2
            echo "SKIP" >> "$TMP_DIR/roslynator.skips"
            continue
        fi
        case "$sev" in
            Error)   severity=high   ;;
            Warning) severity=medium ;;
            Info)    severity=low    ;;
            *)       severity=low    ;;
        esac
        title="$(truncate_str 200 "[$id] $msg")"
        desc="$(truncate_str 2000 "$msg")"
        ft="$(sql_escape "$title")"
        fd="$(sql_escape "$desc")"
        category="$(audit_cs_diagnostic_category "$id")"
        printf "INSERT OR IGNORE INTO findings (file_id, line, tool, source, severity, category, title, description, status) VALUES (%s, %s, 'roslynator', 'static-tool', '%s', '%s', '%s', '%s', 'open');\n" \
            "$fid" "$line" "$severity" "$category" "$ft" "$fd" >> "$batch"
        echo "INS" >> "$TMP_DIR/roslynator.ins"
    done
    attempted="$(count_lines "$TMP_DIR/roslynator.ins")"
    ROSLYNATOR_SKIP="$(count_lines "$TMP_DIR/roslynator.skips")"
    write_batch_footer "$batch"

    if [ "$attempted" -gt 0 ]; then
        result="$(apply_batch roslynator "$batch" "$attempted")"
        ROSLYNATOR_NEW="${result% *}"
        ROSLYNATOR_DUP="${result#* }"
    fi
}

# ---- frontend toolchain probe ----------------------------------------
# All three frontend drivers run tools out of immichFrame.Web/node_modules,
# which a fresh clone does not have. They probe for it and report state
# `missing` with a "run npm ci" notice, exactly as scan_roslynator does for an
# absent analyzer directory.
#
# A driver NEVER runs `npm install` or `npm ci` itself. A scan reads the tree;
# installing would mutate dependencies (and the lockfile's resolution) behind
# the operator's back, which is a different and much larger operation than
# "seed some findings".
AUDIT_WEB_NODE_MODULES="${AUDIT_WEB_NODE_MODULES:-immichFrame.Web/node_modules}"

# audit_web_bin <name>: print the ABSOLUTE path of a locally-installed frontend
# binary, or nothing when node_modules is absent or incomplete. Absolute because
# every caller invokes it from inside a `cd "$AUDIT_WEB_ROOT"` subshell, where a
# repo-relative path no longer resolves.
# Always returns 0 — the callers test the printed value, and a non-zero return
# from a command substitution would trip the core's `set -e`.
audit_web_bin() {
    case "$AUDIT_WEB_NODE_MODULES" in
        /*) _af_web_bin="$AUDIT_WEB_NODE_MODULES/.bin/$1" ;;
        *)  _af_web_bin="$REPO_ROOT/$AUDIT_WEB_NODE_MODULES/.bin/$1" ;;
    esac
    if [ -x "$_af_web_bin" ]; then
        printf '%s' "$_af_web_bin"
    fi
    return 0
}

# audit_web_deps_notice <what>: explain why a frontend driver is standing down.
# Distinguishes "no dependency tree at all" from "tree present, this tool
# missing from it" so a partial install is not misread as a fresh clone.
audit_web_deps_notice() {
    if [ -d "$AUDIT_WEB_NODE_MODULES" ]; then
        echo "  [!] $1 not found under $AUDIT_WEB_NODE_MODULES/.bin"
    else
        echo "  [!] $AUDIT_WEB_NODE_MODULES is absent, so $1 cannot run"
    fi
    echo "      run 'npm --prefix $AUDIT_WEB_ROOT ci' (a scan never installs dependencies itself)"
}

# ---- eslint ----------------------------------------------------------
# ESLint 9 flat config (immichFrame.Web/eslint.config.js), layering the JS
# recommended set, typescript-eslint, eslint-plugin-svelte and
# eslint-config-prettier. It is run from immichFrame.Web because flat config is
# resolved from the working directory: invoked at the repo root, ESLint looks
# for a config that is not there and refuses.
#
# Prettier is deliberately NOT a driver even though `npm run lint` is
# `prettier --check . && eslint .`. Formatting diffs are noise in a findings
# table, the same reasoning that kept `dotnet format` out of the C# half.
scan_eslint() {
    echo "[4/6] eslint..."
    _af_eslint="$(audit_web_bin eslint)"
    if [ -z "$_af_eslint" ]; then
        audit_web_deps_notice eslint
        return
    fi
    out="$TMP_DIR/eslint.json"
    rc=0
    # ESLint exit codes: 0 clean, 1 "lint errors were reported", 2 fatal
    # (bad config, crashed plugin). 1 is the normal outcome for a repo with
    # findings, so only >1 is a failure. Reset rc first — it is a plain global
    # in the sourced adapter and an earlier driver's value would leak in.
    ( cd "$AUDIT_WEB_ROOT" && "$_af_eslint" . --format json ) \
        > "$out" 2>"$TMP_DIR/eslint.err" || rc=$?
    if [ "$rc" -gt 1 ]; then
        echo "  [!] eslint failed (exit ${rc}); see $TMP_DIR/eslint.err" >&2
        return
    fi
    # -s is load-bearing: `jq -e 'type == "array"'` on an EMPTY file produces
    # no output and exits 0, so an eslint run that wrote nothing at all would
    # pass this guard and be reported as "ran, 0 new" — indistinguishable from
    # a clean tree. Slurping asserts "exactly one document, and it is an
    # array", which an empty file fails.
    if ! jq -e -s 'length == 1 and (.[0] | type == "array")' "$out" >/dev/null 2>&1; then
        echo "  [!] no parsable JSON report from eslint; see $TMP_DIR/eslint.err" >&2
        return
    fi
    # State set only after the report is known good, for the reason spelled out
    # in scan_roslynator: "ran, 0 new" must mean a clean tree, never a bail-out.
    ESLINT_STATE=ran

    # One "path|line|severity|ruleId|message" record per message. `message` is
    # LAST so a '|' inside it lands in the final read variable untouched, and
    # newlines are folded to spaces so one diagnostic stays one record (a fatal
    # parse error's message is multi-line). ruleId is null for those fatal
    # messages, hence the fallback.
    jq -r '.[] | .filePath as $f | .messages[]
           | "\($f)|\(.line // 0)|\(.severity)|\(.ruleId // "fatal")|\(.message | gsub("[\r\n]+"; " "))"' \
        "$out" > "$TMP_DIR/eslint.records" 2>/dev/null \
        || : > "$TMP_DIR/eslint.records"
    if [ ! -s "$TMP_DIR/eslint.records" ]; then
        return
    fi

    batch="$TMP_DIR/eslint.sql"
    write_batch_header "$batch"
    while IFS='|' read -r file line sev rule msg; do
        [ -z "$file" ] && continue
        rel="$(rel_path "$file")"
        fid="$(lookup_fid "$rel")"
        if [ -z "$fid" ]; then
            # ESLint lints the whole immichFrame.Web tree, which includes the
            # config files above src/ and the generated immichFrameApi.ts —
            # none of them tracked. Counting them as skips is honest: they were
            # reported and not stored.
            echo "  [skip] untracked path: $rel" >&2
            echo "SKIP" >> "$TMP_DIR/eslint.skips"
            continue
        fi
        # severity 2 = error, 1 = warning. Everything is seeded, errors and
        # warnings alike; the severity mapping is what lets the sweep triage.
        case "$sev" in
            2)  severity=medium; category=bugs        ;;
            *)  severity=low;    category=refactoring ;;
        esac
        # The rule id goes in the title so a finding is identifiable at a
        # glance and so two different rules on the same line stay two findings
        # under idx_findings_dedup(file_id, line, tool, title).
        title="$(truncate_str 200 "[$rule] $msg")"
        desc="$(truncate_str 2000 "$msg")"
        ft="$(sql_escape "$title")"
        fd="$(sql_escape "$desc")"
        printf "INSERT OR IGNORE INTO findings (file_id, line, tool, source, severity, category, title, description, status) VALUES (%s, %s, 'eslint', 'static-tool', '%s', '%s', '%s', '%s', 'open');\n" \
            "$fid" "$line" "$severity" "$category" "$ft" "$fd" >> "$batch"
        echo "INS" >> "$TMP_DIR/eslint.ins"
    done < "$TMP_DIR/eslint.records"
    attempted="$(count_lines "$TMP_DIR/eslint.ins")"
    ESLINT_SKIP="$(count_lines "$TMP_DIR/eslint.skips")"
    write_batch_footer "$batch"

    if [ "$attempted" -gt 0 ]; then
        result="$(apply_batch eslint "$batch" "$attempted")"
        ESLINT_NEW="${result% *}"
        ESLINT_DUP="${result#* }"
    fi
}

# ---- svelte-check ----------------------------------------------------
# The frontend's type checker (`npm run check`); the project has no direct
# `tsc` step. `svelte-kit sync` has to run first — it generates
# .svelte-kit/types and .svelte-kit/tsconfig.json, without which every
# ./$types import fails to resolve and the report is a wall of phantom errors.
# That is generation of gitignored build output, not a dependency install, so a
# scan may do it; the `check` npm script does the same thing.
#
# Output format: `--output machine-verbose` rather than the plain `machine`.
# Both are one line per diagnostic prefixed by a timestamp, but `machine`
# spells a diagnostic as
#     <ts> ERROR "<file>" <line>:<col> "<message>"
# with the path and the message JSON-quoted — so a message containing an
# escaped quote has to be un-escaped by hand. `machine-verbose` emits the same
# record as a JSON object, which jq (already a hard dependency of the kit)
# parses exactly, and it additionally carries `source` and `code` — the pair
# that gives each finding a stable, identifiable id in its title. Verified
# against svelte-check 4's MachineFriendlyWriter.
#
# Filenames in both machine formats are relative to the workspace root, NOT
# absolute as ESLint's are, so they are prefixed with immichFrame.Web/ before
# lookup. Hints never appear: --threshold defaults to `warning`, and the writer
# maps anything below Warning to no type at all.
scan_sveltecheck() {
    echo "[5/6] svelte-check..."
    _af_svelte_check="$(audit_web_bin svelte-check)"
    _af_svelte_kit="$(audit_web_bin svelte-kit)"
    if [ -z "$_af_svelte_check" ] || [ -z "$_af_svelte_kit" ]; then
        audit_web_deps_notice svelte-check
        return
    fi
    rc=0
    ( cd "$AUDIT_WEB_ROOT" && "$_af_svelte_kit" sync ) \
        > "$TMP_DIR/sveltecheck.sync" 2>&1 || rc=$?
    if [ "$rc" -ne 0 ]; then
        echo "  [!] 'svelte-kit sync' failed (exit ${rc}); see $TMP_DIR/sveltecheck.sync" >&2
        return
    fi
    out="$TMP_DIR/sveltecheck.txt"
    rc=0
    # Exit 1 means "errors were reported" — the normal outcome we are here for.
    ( cd "$AUDIT_WEB_ROOT" && "$_af_svelte_check" \
        --tsconfig ./tsconfig.json --output machine-verbose ) \
        > "$out" 2>"$TMP_DIR/sveltecheck.err" || rc=$?
    if [ "$rc" -gt 1 ]; then
        echo "  [!] svelte-check failed (exit ${rc}); see $TMP_DIR/sveltecheck.err" >&2
        return
    fi
    # A crashed run still exits 1 and prints a FAILURE line instead of
    # COMPLETED. Requiring COMPLETED is what stops that being reported as
    # "ran, 0 new", i.e. indistinguishable from a clean type-check.
    if ! grep -q ' COMPLETED ' "$out"; then
        echo "  [!] svelte-check did not complete; see $TMP_DIR/sveltecheck.err" >&2
        return
    fi

    # Strip the millisecond timestamp prefix and drop the three plain-text
    # status lines the writer emits (START / COMPLETED / FAILURE). Everything
    # else is expected to be a diagnostic object and is passed through to the
    # guard below UNFILTERED — deliberately. An earlier `grep '^{'` here would
    # have silently discarded any line that was not JSON, which is precisely
    # the class of corruption the guard exists to catch; narrowing the filter
    # to the three known-good literals means stray output trips the guard
    # instead of vanishing. `sed` without -n passes non-matching lines through
    # for the same reason: a line with no timestamp prefix is also anomalous.
    ndjson="$TMP_DIR/sveltecheck.ndjson"
    sed 's/^[0-9][0-9]* //' "$out" \
    | grep -Ev '^(START|COMPLETED|FAILURE)([[:space:]]|$)' > "$ndjson" || :

    # Whole-document guard, the counterpart of scan_eslint's `type == "array"`
    # and scan_npmaudit's `has("vulnerabilities")`. The streaming NDJSON form
    # otherwise has none, and it needs one MORE than they do: jq validates each
    # line as it goes, so on a malformed line it exits non-zero having ALREADY
    # WRITTEN every good record before it. Recovering with `|| : > records`
    # would then truncate a partly-good report to nothing and the driver would
    # report "ran, 0 new" — indistinguishable from a clean type-check, the same
    # trap scan_roslynator's exit-code handling exists to avoid. Slurping the
    # whole stream first, and only setting the state once it parses, makes a
    # malformed line visible instead of silent. An empty stream slurps to [],
    # and `all` over an empty array is true, so a clean run passes.
    if ! jq -e -s 'all(type == "object")' "$ndjson" >/dev/null 2>&1; then
        echo "  [!] unparsable diagnostic stream from svelte-check; see $ndjson" >&2
        return
    fi
    SVELTECHECK_STATE=ran

    # Emit "path|line|type|source/code|message". Positions are 0-based, hence
    # +1. The stream is already known to parse, so `|| :` here only satisfies
    # `set -e`; note it does NOT truncate the output file, so any records jq
    # did write survive.
    jq -r 'select(.type == "ERROR" or .type == "WARNING")
           | "\(.filename)|\(.start.line + 1)|\(.type)|\(.source // "svelte-check")/\(.code // "?")|\(.message | gsub("[\r\n]+"; " "))"' \
        "$ndjson" > "$TMP_DIR/sveltecheck.records" 2>"$TMP_DIR/sveltecheck.jqerr" || :
    if [ ! -s "$TMP_DIR/sveltecheck.records" ]; then
        return
    fi
    batch="$TMP_DIR/sveltecheck.sql"
    write_batch_header "$batch"
    while IFS='|' read -r file line kind code msg; do
        [ -z "$file" ] && continue
        rel="$(rel_path "$AUDIT_WEB_ROOT/$file")"
        fid="$(lookup_fid "$rel")"
        if [ -z "$fid" ]; then
            echo "  [skip] untracked path: $rel" >&2
            echo "SKIP" >> "$TMP_DIR/sveltecheck.skips"
            continue
        fi
        case "$kind" in
            ERROR) severity=medium; category=bugs        ;;
            *)     severity=low;    category=refactoring ;;
        esac
        title="$(truncate_str 200 "[$code] $msg")"
        desc="$(truncate_str 2000 "$msg")"
        ft="$(sql_escape "$title")"
        fd="$(sql_escape "$desc")"
        printf "INSERT OR IGNORE INTO findings (file_id, line, tool, source, severity, category, title, description, status) VALUES (%s, %s, 'sveltecheck', 'static-tool', '%s', '%s', '%s', '%s', 'open');\n" \
            "$fid" "$line" "$severity" "$category" "$ft" "$fd" >> "$batch"
        echo "INS" >> "$TMP_DIR/sveltecheck.ins"
    done < "$TMP_DIR/sveltecheck.records"
    attempted="$(count_lines "$TMP_DIR/sveltecheck.ins")"
    SVELTECHECK_SKIP="$(count_lines "$TMP_DIR/sveltecheck.skips")"
    write_batch_footer "$batch"

    if [ "$attempted" -gt 0 ]; then
        result="$(apply_batch sveltecheck "$batch" "$attempted")"
        SVELTECHECK_NEW="${result% *}"
        SVELTECHECK_DUP="${result#* }"
    fi
}

# ---- npm audit -------------------------------------------------------
# The frontend's counterpart to scan_vulnerable: `npm audit` reports per
# package, not per source line, so every finding is attributed to
# immichFrame.Web/package.json — the file where a bump is actually made —
# exactly as the NuGet advisories are attributed to Directory.Packages.props.
# Transitive packages have no entry in package.json, so they get line 0.
scan_npmaudit() {
    echo "[6/6] npm audit..."
    if ! command -v npm >/dev/null 2>&1; then
        echo "  [!] npm not installed — install Node.js"
        return
    fi
    if [ ! -d "$AUDIT_WEB_NODE_MODULES" ]; then
        audit_web_deps_notice "npm audit"
        return
    fi
    out="$TMP_DIR/npmaudit.json"
    # Exits non-zero whenever any vulnerability is reported — the normal case —
    # so tolerate it and let the parse decide. Needs network access to query
    # the advisory registry; offline it fails and the guard below reports it.
    npm --prefix "$AUDIT_WEB_ROOT" audit --json \
        > "$out" 2>"$TMP_DIR/npmaudit.err" || true
    # Slurped for the same reason as scan_eslint's guard: `jq -e 'has(...)'` on
    # an EMPTY file exits 0, and an empty file is exactly what npm leaves
    # behind when the command dies before writing a report.
    if ! jq -e -s 'length == 1 and (.[0] | has("vulnerabilities"))' "$out" >/dev/null 2>&1; then
        echo "  [!] no parsable audit report from npm; see $TMP_DIR/npmaudit.err" >&2
        return
    fi
    NPMAUDIT_STATE=ran

    owner="$AUDIT_WEB_ROOT/package.json"
    fid="$(lookup_fid "$owner")"
    if [ -z "$fid" ]; then
        echo "  [skip] untracked path: $owner" >&2
        NPMAUDIT_SKIP=1
        return
    fi

    # Second pass over the PRODUCTION dependency graph only. npm's report does
    # not say whether a vulnerable package is reachable at runtime, and that
    # matters a lot for triage: this project declares nothing but
    # devDependencies, so every advisory here is against build tooling
    # (postcss, brace-expansion, js-yaml, nanoid, fast-uri). Seeded at face
    # value they would put 9 high-severity rows at the top of the queue and
    # bury the genuine findings.
    #
    # They are not dropped — a compromised build dependency can still reach the
    # shipped bundle — but seeded ONE SEVERITY LEVEL LOWER, with "dev
    # dependency" in the title so the reason is visible without opening the
    # row. Severity mapping is how volume is managed here, exactly as it is for
    # the C# analyzers; filtering is not.
    #
    # Asking npm rather than reading package.json's devDependencies block is
    # deliberate: a transitive package can be reachable from both graphs, and
    # only npm knows.
    #
    # The result is gated on an explicit success flag, NOT on the name file
    # being non-empty, because in this repo those two are byte-identical. There
    # is no `dependencies` block at all — only devDependencies — so a SUCCESSFUL
    # --omit=dev pass reports zero vulnerabilities and writes an empty file,
    # exactly as a registry timeout would. Keying the downgrade off emptiness
    # would silently downgrade every advisory whenever this second call failed,
    # and the output would be indistinguishable from a correct run. With the
    # flag, a failure leaves every advisory at PRODUCTION severity — the
    # conservative direction, since over-reporting a build-only CVE is a triage
    # cost while under-reporting a runtime one is a miss.
    #
    # The flag also covers a partial write: the `keys[]` jq is part of the &&
    # chain, so if it dies mid-stream the flag stays 0 and the truncated name
    # list is never consulted.
    _af_prod_ok=0
    prod="$TMP_DIR/npmaudit.prod.json"
    npm --prefix "$AUDIT_WEB_ROOT" audit --json --omit=dev \
        > "$prod" 2>"$TMP_DIR/npmaudit.prod.err" || true
    if jq -e -s 'length == 1 and (.[0] | has("vulnerabilities"))' "$prod" >/dev/null 2>&1 \
       && jq -r '.vulnerabilities | keys[]' "$prod" \
            > "$TMP_DIR/npmaudit.prodnames" 2>/dev/null; then
        _af_prod_ok=1
    else
        echo "  [!] production-graph pass failed; every advisory kept at full severity" >&2
    fi

    # .vulnerabilities is an object keyed by package name; each value carries a
    # `via` array whose OBJECT entries are advisories and whose STRING entries
    # are just chain references to another key in the same map (skipped here —
    # that package reports its own advisory in its own entry). `unique`
    # collapses the repeats npm emits when one advisory reaches a package by
    # several dependency paths. `title` is LAST so a '|' inside it survives the
    # read below.
    jq -r '[ .vulnerabilities[]? | .name as $n
             | (.via[]? | select(type == "object")
                | "\($n)|\(.severity)|\(.url)|\(.title | gsub("[\r\n]+"; " "))") ]
           | unique | .[]' "$out" > "$TMP_DIR/npmaudit.records" 2>/dev/null \
        || : > "$TMP_DIR/npmaudit.records"
    if [ ! -s "$TMP_DIR/npmaudit.records" ]; then
        return
    fi

    batch="$TMP_DIR/npmaudit.sql"
    write_batch_header "$batch"
    while IFS='|' read -r name sev url atitle; do
        [ -z "$name" ] && continue
        # Line of the declaration in package.json, 0 when absent (the normal
        # case for a transitive dependency). -F because scoped package names
        # are dotted and slashed and would otherwise read as a regex.
        line="$(grep -Fn "\"$name\":" "$owner" 2>/dev/null | head -1 | cut -d: -f1)"
        [ -z "$line" ] && line=0
        case "$sev" in
            critical) severity=critical ;;
            high)     severity=high     ;;
            moderate) severity=medium   ;;
            low)      severity=low      ;;
            *)        severity=medium   ;;
        esac
        # Dev-only advisory: not reachable from the production graph, so step
        # the severity down one rung (low is the floor) and say so in the
        # title. Gated on _af_prod_ok — when the production pass did not
        # succeed the name list means nothing and everything stays at full
        # severity. See the --omit=dev pass above.
        kind="package"
        if [ "$_af_prod_ok" = 1 ] && ! grep -Fxq "$name" "$TMP_DIR/npmaudit.prodnames"; then
            kind="dev dependency"
            case "$severity" in
                critical) severity=high   ;;
                high)     severity=medium ;;
                medium)   severity=low    ;;
                *)        severity=low    ;;
            esac
        fi
        # Advisory id = last path segment of the URL (GHSA-xxxx-...). In the
        # title so two advisories against the same package stay two findings
        # under idx_findings_dedup(file_id, line, tool, title). jq renders a
        # missing url as the literal string "null", which ${url##*/} would pass
        # through as an advisory id, so that spelling is normalised away here —
        # otherwise the empty-string fallback below could never fire.
        [ "$url" = "null" ] && url=""
        adv="${url##*/}"
        [ -z "$adv" ] && adv="$sev"
        title="$(truncate_str 200 "[$adv] vulnerable $kind $name")"
        # The advisory URL is appended only when there is one, so a null url
        # does not leave the description ending in a stray space.
        ref=""
        [ -n "$url" ] && ref=" $url"
        desc="$(truncate_str 2000 "$sev severity advisory against $name ($kind) — $atitle. Bump the dependency in $owner (and refresh $AUDIT_WEB_ROOT/package-lock.json).$ref")"
        ft="$(sql_escape "$title")"
        fd="$(sql_escape "$desc")"
        printf "INSERT OR IGNORE INTO findings (file_id, line, tool, source, severity, category, title, description, status) VALUES (%s, %s, 'npmaudit', 'static-tool', '%s', 'security', '%s', '%s', 'open');\n" \
            "$fid" "$line" "$severity" "$ft" "$fd" >> "$batch"
        echo "INS" >> "$TMP_DIR/npmaudit.ins"
    done < "$TMP_DIR/npmaudit.records"
    attempted="$(count_lines "$TMP_DIR/npmaudit.ins")"
    write_batch_footer "$batch"

    if [ "$attempted" -gt 0 ]; then
        result="$(apply_batch npmaudit "$batch" "$attempted")"
        NPMAUDIT_NEW="${result% *}"
        NPMAUDIT_DUP="${result#* }"
    fi
}

# ---------------------------------------------------------------------------
# Architecture report — not implemented
# ---------------------------------------------------------------------------

# audit_arch_preflight: refuse arch-sweep cleanly.
#
# The core's placeholder substitution covers only the optional Section A/B/D/E
# bodies. audit/arch.sh:45 calls this function unguarded, so WITHOUT this stub
# every arch entry point dies with "audit_arch_preflight: not found" — and there
# are three that never touch the Makefile guard: `audit/audit.sh arch-sweep`
# (documented at audit/README.md:45), the command
# .claude/skills/sweep/phase-3-architecture.md tells an agent to run, and
# advance_to_arch_or_idle (audit.sh:772), which calls cmd_arch_sweep on its own
# once Phases 1 and 2 complete.
#
# Returning non-zero makes arch.sh's `|| exit 1` refuse with the message below.
# This stub is deleted when the real audit_arch_* members land.
audit_arch_preflight() {
    echo "arch-sweep: the fullstack adapter implements no audit_arch_* members" >&2
    echo "  (see audit/ADAPTERS.md, 'Architecture report'). Phase 1 (sweep) and" >&2
    echo "  Phase 2 (deep-sweep) are unaffected." >&2
    return 1
}
